### ISSUE TITLE
`http://localhost:50124/deprofane` thows error

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [IAmAnubhavSaini/node-deprofane-service#2]
```
 + REQUEST +  /deprofane at 1617672024325
TypeError: Cannot read property 'replace' of undefined
    at code\github\iamanubhavsaini\node-deprofane-service\src\deprofane.js:8:70
    at Array.reduce (<anonymous>)
    at Object.deprofane [as default] (code\github\iamanubhavsaini\node-deprofane-service\src\deprofane.js:8:36)
    at code\github\iamanubhavsaini\node-deprofane-service\src\service.js:47:50
    at Layer.handle [as handle_request] (code\github\iamanubhavsaini\node-deprofane-service\node_modules\express\lib\router\layer.js:95:5)
    at next (code\github\iamanubhavsaini\node-deprofane-service\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (code\github\iamanubhavsaini\node-deprofane-service\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (code\github\iamanubhavsaini\node-deprofane-service\node_modules\express\lib\router\layer.js:95:5)
    at code\github\iamanubhavsaini\node-deprofane-service\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (code\github\iamanubhavsaini\node-deprofane-service\node_modules\express\lib\router\index.js:335:12)

```

**Comment by IAmAnubhavSaini** [comment]
Resolved!
